apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres_milan_1:5432
    database: druid
    user: druid
    secureJsonData:
      password: FoolishPassword
    isDefault: true
    apiVersion: 1