name: london
volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}
  db: {}
  minio_data: {}
  kb: {}
  db_backup: {}
  druid_db_backup: {}
  backrest_data: {}
  backrest_config: {}
  backrest_cache: {}
  target_volume: {}
  vault_data: {}
  rag_models: {}
  hdfs_namenode: {}
  hdfs-datanode: {}
  hdfs-datanode-2: {}
  metadata_data_2: {}
  hdfs-datanode-3: {}
  minio_data_target: {}

services:
  postgres:
    image: pgedge/pgedge:latest
    volumes:
      - ./database/postgres/db.json:/home/pgedge/db.json
      #- ./database/postgres/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
#   environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      NODE_NAME: postgres-london-2
      PGDATA: /data/pgdata
    env_file:
      - database/environment
    ports:
      - "25432:5432"
    profiles:
      - database
      - not-db-init
      - london_node
    depends_on:
      - hdfs-datanode
    networks:
      london_network:
      shared_network:
        aliases:
          - london_postgres

  zookeeper:
    image: zookeeper:3.5.10
    platform: linux/amd64
    ports:
      - "22181:2181"
    environment:
      - ZOO_MY_ID=1
      #- ZOO_SERVERS=server.1=zookeeper:2888:3888 # Set only a single server
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network

  coordinator:
    image: apache/druid:31.0.0
    platform: linux/amd64
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
      - ./database/druid/upload:/druid/upload
    depends_on:
      - zookeeper
      - postgres
      - hdfs-datanode
    ports:
      - "28081:8081"
    command:
      - coordinator
    env_file:
      - database/environment
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network
      

  broker:
    image: apache/druid:31.0.0
    platform: linux/amd64
    volumes:
      - broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
      - hdfs-datanode
    command:
      - broker
    env_file:
      - database/environment
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network
    

  historical:
    image: apache/druid:31.0.0
    platform: linux/amd64
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
      - hdfs-datanode
    ports:
      - "28083:8083"
    command:
      - historical
    env_file:
      - database/environment
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network

  middlemanager:
    image: apache/druid:31.0.0
    platform: linux/amd64
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
      - ./database/druid/upload:/druid/upload
    depends_on:
      - zookeeper
      - postgres
      - coordinator
      - hdfs-datanode
    ports:
      - "28091:8091"
      - "28100-28105:8100-8105"
    command:
      - middleManager
    env_file:
      - database/environment
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network

  router:
    image: apache/druid:31.0.0
    platform: linux/amd64
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
      - hdfs-datanode
    ports:
      - "28888:8888"
    command:
      - router
    env_file:
      - database/environment
    profiles:
      - database
      - not-db-init
      - london_node
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://router:8888/status/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - london_network

  db:
    env_file:
      - database/.env
    image: pgedge/pgedge:latest
    ports:
      - "25433:5432"
#    environment:
   #   POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      NODE_NAME: test
    volumes:
      - db:/data
      #- ./database/postgres/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      london_network:
      shared_network:
        aliases:
          - london_db

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 29000:9000
      - 29001:9001
    env_file:
      - database/.env
    command: minio server /data
    profiles:
      - database
      - not-db-init
      - london_node
    networks:
      - london_network

  db-init:
    image: ghcr.io/belgio99/smartfactory/db-init:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - database/.env
    profiles:
      - database
      - london_node
    volumes:
      - ./database/druid/upload:/druid/upload
    depends_on:
      router:
        condition: service_healthy
    networks:
      - london_network
      
  kb:
    build:
      context: ./kb
      dockerfile: Dockerfile
    image: ghcr.io/belgio99/smartfactory/kb:latest
    volumes:
      - kb:/KB/storage
    platform: linux/amd64
    ports: 
      - "10010:8000"
    profiles:
      - kb
      - not-db-init
    env_file:
      - database/.env
    networks:
      - london_network
    
  data-processing:
    build:
      context: ./data-processing
      dockerfile: Dockerfile
    image: ghcr.io/belgio99/smartfactory/data-processing:latest
    ports: 
      - "10030:8000"
    profiles:
      - data-processing
      - not-db-init
    env_file:
      - database/.env
      - data-processing/.env
    depends_on:
      router:
        condition: service_healthy
    networks:
      - london_network

  api:
    image: ghcr.io/belgio99/smartfactory/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - "20040:8000"
    env_file:
      - api/.env
      - api/environment
    depends_on:
      - router
    profiles:
      - api
      - not-db-init
      - london_node
    networks:
      - london_network

  smtp:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
        - "11025:1025"
        - "18025:8025"
    environment:
        MH_OUTGOING_SMTP_USERNAME: "noreply@smartfactory.com"
        MH_OUTGOING_SMTP_PASSWORD: "SmartAppPassword123"
    profiles:
      - api
      - not-db-init
    networks:
      - london_network
    
  rag:
    image: ghcr.io/belgio99/smartfactory/rag:latest
    build:
      context: ./rag
      dockerfile: Dockerfile
    env_file:
      - rag/.env
    volumes:
      - kb:/docs/kb
      - rag_models:/app/models
    ports: 
      - "20050:8000"
    profiles:
      - rag
      - not-db-init
    networks:
      - london_network

  gui-panel:
    image: ghcr.io/belgio99/smartfactory/gui-panel:latest
    build:
      context: ./gui-panel
      dockerfile: Dockerfile
    env_file:
      - gui-panel/.env
    ports: 
      - "20060:8080"
    profiles:
      - gui-panel
      - not-db-init
      - london_node
    networks:
      - london_network

  kpi-engine:
    image: ghcr.io/belgio99/smartfactory/kpi-engine:latest
    build:
      context: ./kpi-engine
      dockerfile: Dockerfile
    ports: 
      - "10080:8000"
    profiles:
      - kpi-engine
      - not-db-init
    env_file:
      - kpi-engine/.env
    depends_on:
      router:
        condition: service_healthy
    networks:
      - london_network

  backrest:
    image: garethgeorge/backrest:latest
    hostname: backrest
    volumes:
      - backrest_data:/data
      - ./database/backrest/config:/config
      - backrest_cache:/cache
      - druid_shared:/userdata/druid_shared # [optional] mount local paths to backup here.
      - db_backup:/userdata/db_backup 
      - druid_db_backup:/userdata/druid_db_backup
      - minio_data:/userdata/minio_data
      - target_volume:/target_volume
    #  - /MY-REPOS:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=Europe/Rome # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898
    profiles:
      - database
      - not-db-init
    env_file:
      - database/backrest/.env
    networks:
      - london_network
     
  vault: #it is in dev mode!
    image: hashicorp/vault
    volumes:
      - vault_data:/vault/file
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_STORAGE_BACKEND: "file"  
    ports:
      - "28200:8200"
    profiles:
      - database
      - london_node
    logging:
      driver: "json-file"
      options:
        max-file: "1"
    networks:
      - london_network

  hdfs-namenode:
    image: bde2020/hadoop-namenode:latest
    environment:
      - CLUSTER_NAME=smartfactory-cluster
    ports:
      - "9870:9870"  # Namenode Web UI
    #  - "19000:9000"  # Namenode RPC
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    profiles:
      - database
    env_file:
      - database/hdfs/hadoop.env
    networks:
      london_network:
      shared_network:
        aliases:
          - london_namenode

  hdfs-datanode:
    image: bde2020/hadoop-datanode:latest
    environment:
      - "SERVICE_PRECONDITION=milan_namenode:9870"
    ports:
      - "29864:9864"  # Datanode Web UI
      #- "50010:50010"  # DataNode Data Transfer
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    profiles:
      - database
      - london_node
    env_file:
      - database/hdfs/hadoop.env
    networks:
      london_network:
      shared_network:
        aliases:
          - london_datanode

networks:
  london_network:
    name: london_network
  shared_network:
    name: shared_network